production:
  adapter: mysql2
  database: time_tracker_production

development:
  adapter: mysql2
  database: time_tracker_development

test: &test
  adapter: mysql2
  database: time_tracker_test

cucumber:
  <<: *test
